import Head from "next/head"

import SliderComponent from "../components/SliderComponent"

import { getAllSliderImages } from "../lib/db/slider-images"

export default function HomePage({ sliderImages }) {
  return (
    <div>
      <Head>
        <title>Combits | CUI Attock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderComponent sliderImages={sliderImages} />
    </div>
  )
}

export async function getServerSideProps() {
  const sliderImages = JSON.parse(JSON.stringify(await getAllSliderImages()))

  return {
    props: {
      sliderImages,
    },
  }
}
