import Head from "next/head"
import SliderComponent from "../components/SliderComponent"

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Combits | CUI Attock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderComponent />
    </div>
  )
}
